volumes:
  db:

services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bin
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
