name: binify-cloud

volumes:
  db:

services:
  postgres:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bin
    volumes:
      - db:/home/postgres/pgdata/data
    ports:
      - "5432:5432"
